---
- name: Install app
  hosts: default
  become_user: root
  vars:
    user: "root"
    password: "toor"
  vars_files:
    - vars.yml
  become: true
  roles:
    - bootstrap
    - docker
    - deploy
